name: Lighthouse Check

on:
  page_build:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        repository: 'sitdisch/cloud'
        persist-credentials: false
    - uses: actions/checkout@master
      with:
        repository: 'mythemeway/lighthouse-badges'
        persist-credentials: false
        path: nested
    - name: Create Results
      run: |
        cd nested
        ./src/index.js -u https://mythemeway.github.io/Dark-Particle/ https://mythemeway.github.io/Dark-Particle/projects/2020/10/31/project-1.html -r -b plastic -o dark-particle/mobile
        export LIGHTHOUSE_BADGES_PARAMS="--preset=desktop"
        ./src/index.js -u https://mythemeway.github.io/Dark-Particle/ https://mythemeway.github.io/Dark-Particle/projects/2020/10/31/project-1.html -r -b plastic -o dark-particle/desktop
        cp -r dark-particle ../lighthouse-results/
        cd ..
    - name: Commit Results
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add lighthouse-results/dark-particle
        git commit -am "Lighthouse Results Refreshed | Dark-Particle"
    - name: Push Results
      uses: ad-m/github-push-action@master
      with:
        repository: 'sitdisch/cloud'
        github_token: ${{ secrets.SITDISCH_REPO_TOKEN }}
